### ISSUE TITLE
Assignment 4: press release

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#11]
This week we are going to write a press release announcing some hacktivist action that has not actually transpired. The text should serve to model in your head, and your readers’ heads, some possibility of an action _as if it has occurred_, and explain why it matters.

Treat the press release as an independent artifact. You do not need to use your own voice, you can write in the voice of some imaginary organization or pseudonym as you see fit. The first paragraph should contain a lead sentence that states the facts of what happened, then should give some context for what the implications of that action are.

Use the text of the press release to tell a story that helps us understand what (allegedly) happened, what the stakes are, and any other context that might help us to support the cause you're advocating for.

Steps:
1. Create a new [GitHub Gist](https://gist.github.com/)
2. Write your press release
3. Comment below with a link to your Gist

Here are some resources that might help you:
* [SNCC Rock Hill sit-in](https://www.crmvet.org/docs/pr/6102_rockhill-pr.pdf) ([more examples from the Civil Rights movement](https://www.crmvet.org/docs/pr/prdocs.htm))
* [Sunrise Movement sit-in](https://medium.com/sunrisemvmt/statement-from-varshini-prakash-founder-of-sunrise-movement-after-hundreds-of-young-people-f5237ebfa7c9) ([more from Sunrise](https://medium.com/sunrisemvmt/statement-from-varshini-prakash-founder-of-sunrise-movement-after-hundreds-of-young-people-f5237ebfa7c9))
* [CBS News: How To Write a Press Release, With Examples](https://www.cbsnews.com/news/how-to-write-a-press-release-with-examples/)
* [The Most Amazing Press Release Ever Written](https://www.prnewswire.com/news-releases/the-most-amazing-press-release-ever-written-113302099.html)
* [New York Times Special Edition](https://visitsteve.com/made/the-ny-times-special-edition/) (not a press release, but a good example of modelling a possible reality through media)

**Comment by youngcc3157** [comment]
https://gist.github.com/youngcc3157/cfa88252135d258ec0b1773387ff2f8d

**Comment by ChristinavanHal** [comment]
https://gist.github.com/ChristinavanHal/1982f841a3754440d39c7e926d5c2f16

**Comment by mlhawks12** [comment]
https://gist.github.com/mlhawks12/cb4b1b0b6f4c1dac270bcd85f952a19b

**Comment by Salomr** [comment]
https://gist.github.com/Salomr/c88e9ba372fe420850e66af5c07b16fa

**Comment by schafc** [comment]
https://gist.github.com/schafc/8cd1d21db93ab77aa1325be62779f156

**Comment by tcyrus** [comment]
This seems important to link first: [Mastering Markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by tcyrus** [comment]
[My Press Release](https://gist.github.com/tcyrus/50429febb24fe9760a6ba960adf48d70)

**Comment by bfblake** [comment]
https://gist.github.com/bfblake/f4062f9fb669eb26f1b0842368b3846f

**Comment by Brandonkl** [comment]
https://gist.github.com/Brandonkl/eb20c887f24fcf83fd395b1ae14deac3

**Comment by jlyon1** [comment]
https://gist.github.com/jlyon1/098b7303bb83b56ae0e08db58b44fc35

**Comment by CrispyJimbo** [comment]
https://gist.github.com/CrispyJimbo/97e59962e3dadcf715baa5353bc52a2a

**Comment by jordanchappel32** [comment]
https://gist.github.com/jordanchappel32/4bc6ba154efa49cdb7c132fb83e35e75

**Comment by arthurmosley** [comment]
[https://gist.github.com/arthurmosley/a47dcafb92a6467fc7906636a4718a64](url)

**Comment by mruskamp** [comment]
https://gist.github.com/mruskamp/3204eaf8d676345405b9fdc8a9b38bef

**Comment by cmharsh** [comment]
https://gist.github.com/cmharsh/2fa94bdd2079f08b13ec6a34d1cbaa19#file-new-press-release-from-the-wsj

**Comment by KeranosGodofStorms** [comment]
**<script src="https://gist.github.com/KeranosGodofStorms/d87a776cbbcd66fc35dfa10bee1194bc.js"></script>**

**Comment by KeranosGodofStorms** [comment]
https://gist.github.com/KeranosGodofStorms/d87a776cbbcd66fc35dfa10bee1194bc

**Comment by verghv5** [comment]
<script src="https://gist.github.com/verghv5/c7779334dfc0a65f6d5c60158381b99a.js"></script>
