### ISSUE TITLE
Assignment 5: Press Release Redux

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#12]
This is a follow-up to last week's [Press Release assignment](https://github.com/dphiffer/hacktivism/issues/11). Compelling text requires multiple drafts, after receiving feedback from peers. This week we will offer our most generous selves in providing feedback on each other's press releases, and then use that peer feedback to help craft a better, more effective version of the text.

1. Due _Tuesday October 15_: read the other [press releases](https://github.com/dphiffer/hacktivism/issues/11) and leave brief and constructive comments for your fellow classmates. You don't need to comment on each and every text, but you should at least a few comments.
2. Due _Saturday October 19_: using the feedback from your classmates, write a second draft of your press release. Create a [new GitHub gist](https://gist.github.com/new), give it a filename `[last name]_[first name].md`, and try to incorporate some [Markdown formatting](https://guides.github.com/features/mastering-markdown/) (shout out to Tim for this link). Leave a comment below with a link to your press release gist.

Here are some things to pay attention to:
- which person or group is writing the press release? what is their apparent agenda?
- what "hack" are they describing? is it clear what happened? is it mentioned in the first sentence?
- does the press release give further material to support their cause?
- is it practical? is it funny? should it be done?

**Comment by tcyrus** [comment]
I'm reusing the [same gist](https://gist.github.com/tcyrus/50429febb24fe9760a6ba960adf48d70) so I can track revisions made to the release.

**Comment by cmharsh** [comment]
https://gist.github.com/cmharsh/9d1d2937a19e9d48f4678ac28b48e2fd

**Comment by arthurmosley** [comment]
https://gist.github.com/arthurmosley/2e06f8d53ee81667489df262e4b8608c

**Comment by jordanchappel32** [comment]
https://gist.github.com/jordanchappel32/1b60f5e284b98c6d88b0d763f8d8d02d

**Comment by ChristinavanHal** [comment]
https://gist.github.com/ChristinavanHal/2e0d699c1747363638d97c0c566d0bc0

**Comment by CrispyJimbo** [comment]
https://gist.github.com/CrispyJimbo/5e88a335fa717ff1e26cfad2fa656630

**Comment by schafc** [comment]
https://gist.github.com/schafc/0eb2ca1c6fe6b671ccb17c1d933219b0

**Comment by mruskamp** [comment]
https://gist.github.com/mruskamp/d6d4a71db1767eb3ce8b9b04544f525f

**Comment by Brandonkl** [comment]
https://gist.github.com/Brandonkl/af4376cf70a9db0fa2f5a7ef5289da41

**Comment by Salomr** [comment]
https://gist.github.com/Salomr/534d4fbf85275f3ae5d2b29f1892459f

**Comment by mlhawks12** [comment]
https://gist.github.com/mlhawks12/65846700e08db8a9ba341b0917239382

**Comment by youngcc3157** [comment]
https://gist.github.com/youngcc3157/cfa88252135d258ec0b1773387ff2f8d

**Comment by jlyon1** [comment]
https://gist.github.com/jlyon1/098b7303bb83b56ae0e08db58b44fc35

**Comment by bfblake** [comment]
https://gist.github.com/bfblake/5d42b12dd6aba8a732fd726fe71b9fde

**Comment by KeranosGodofStorms** [comment]
https://gist.github.com/KeranosGodofStorms/7c01f7985960b2c647fcae9dae895406
