### ISSUE TITLE
Assignment 6: Dance for solidarity

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#13]
1. Read the about page for [Dances for Solidarity](https://www.dancesforsolidarity.org/about-1-1)
2. Take 15 minutes alone in a room and do the [10 step dance for solidarity](https://www.dancesforsolidarity.org/the-dance-for-solidarity)
3. Write a brief reflection about your experience in the comments here

**Comment by Brandonkl** [comment]
I found the dance to be very refreshing and physically liberating as most of the steps are not at all common motions we do in our day to day life. It is pretty humbling to consider that such arbitrary movements are not only repeated by others, but that actually are a unification to those who are incarcerated and in solitary confinement. What is most interesting about this dance to me, is that it is a transfer of information between people in different 'realms' as stated on the website, but the content of this information is completely indefinable through language and is more directly related to the IDEA OF such a communication between those in isolation and those on the outside; it is meaningful in its purpose without actually having any content, very interesting and refreshing.

**Comment by ChristinavanHal** [comment]
It was interesting. It kind of reminded me of the dance warm-up we did in elementary school. We also had the exact same steps in learning ballet arm movements. It's actually pretty easy to learn (albeit, I forget all the steps already) and was oddly simple when compared to the various dance sequences I have performed during my life. The mixture of Yoga, ballet, and spontaneity was kind of fun. It almost seemed like something you could do with the family with little kids.

**Comment by mlhawks12** [comment]
My experience was very relaxing. I did this assignment in the middle of a long marathon of studying. It was nice to get up and move in the small space I was in. I can see how the movements for the incarcerated people could be very liberating. Also that the communication with the outside world show them that they aren't alone

**Comment by schafc** [comment]
Performing the 10 step dance for solidarity was an interesting experience. I ended up running through it twice, as the first time I did it, I had to keep stopping to check the steps page. Overall, the dance made me focus a lot on my body and how it was moving, with a lot of focus put on remembering subsequent steps. It was easier the second time though, and I think with practice and repetition it would  become easier, and I'd be able to focus more on the ideas it represents than simply on not accidentally running into anything. Finally, I think the concept of the dance is neat, as there are a lot of people who are impacted by the prison system, and it is important to remember that, even if some of them did bad things.

**Comment by garoller** [comment]
I experienced relief during and after the 10 step dance for solidarity. Sometimes it is difficult to "get out of my own head", so to speak, and the dance allowed me to focus on something other than stressors, issues, or anxiety, however small, that I am currently dealing with. I can see how other people, including those that are incarcerated, might have similar experiences when doing this dance, as it could allow them to focus on a defined task, which could lead to some stress relief and increased positivity.

**Comment by jlyon1** [comment]
The 10 step dance for solidarity is clearly designed to help relieve tension and stress. I feel that it does a good job at accomplishing this goal. The added benefit of having a dance designed for incarcerated individuals is that you may do this dance as a way to engage with those you cannot directly communicate with. I'd imagine for those incarcerated individuals this provides a little bit of support.

**Comment by Salomr** [comment]
You know this was interesting. I was worried that someone would see me doing this weird ass dance through my window, but then the idea hit me that no one would see people in solitary doing this which would probably help them feel more free to do something like this.

**Comment by KeranosGodofStorms** [comment]
The dance itself feels more like a meditation exercise than anything else. I sort of understand the point of the dance. The point being that you're pretending to stretch while simultaneously being in a tight space to simulate being in a cell like the inmates who came up with the dance. I just think that there isn't enough emphasis on the limitation of movement. They only really mention it in step 4 and it would strengthen the theme of meditation in a limiting environment. Still, it's pretty cool that someone came up with the idea to support people in prison in this way.

**Comment by cmharsh** [comment]
In a sober state, I'm not much of a dancer.  However, this gave the opportunity to really "dance like nobody is watching" which is especially pertinent given the fact that when one is in solitary confinement, nobody really is watching you.  What I noticed most about the dance was that it seemed tailored to give a feeling of loftiness and space to the one performing it.  I believe that the dance moves were chosen in this way to perhaps give those incarcerated a brief release from their very real and very small accommodations by performing a wild and expansive dance.  This is further supported by the language used to describe the dance -  "walk in the biggest circle possible [...] feel your body grow lighter and lighter, as if you are a cloud."

**Comment by mruskamp** [comment]
My experience with this dance provided me with a sense of general relief. I think that focusing only on performing these sort of odd movements takes one's mind away from whatever stressors and anxiety its facing. I just felt very at ease. Doing the dance made me see why it might be particularly cathartic for people in solitary confinement; you can easily imagine yourself being anywhere pleasant, which would be particularly nice for incarcerated people. 

It is hard to speak on this other aspect from a personal point of view, as I'm not in solitary confinement myself, but I'd also imagine some spiritual level of relief or comfort in knowing that others who are alone are performing this dance with you. I would have to image that adds another dimension to performing the dance.

**Comment by bfblake** [comment]
As others mentioned above, it felt much more like a meditation than a dance to me. At the same time, the elements involving rapid movement and rapid changes were definitely almost directly oppositional to traditional meditation. I believe this distinction is because whereas meditation is typically meant to ground us after constantly being on the move and outside of our heads, the dance would be meant to ground the incarcerated who are constantly confined and inside their own heads. Additionally, I found step 4 interesting, because I figured that retracing the bounds of the space I was in via walking "in the biggest circle possible" would feel confining, but after doing so I didn't get that sensation at all.

**Comment by jordanchappel32** [comment]
I'll be honest: I approached this assignment with a huge amount of skepticism. However, I gave it a fair shot, pushed some furniture in my room towards the walls, and.... not much. I did not feel any sort of connection to others or relief from the dance. If I felt anything, I would say that steps 2 and 3 made me more self-aware of the different muscles and parts of my body. 

I do see how doing this dance throughout the day could give someone in solitary confinement a sense of routine, which could be beneficial, but other than that I'm not sure what benefits I see. I wonder how many inmates even would remember the dance once placed in solitary confinement, as I doubt they would take it seriously. If a group of inmates did actually make this part of their routine, I could see how it would help them feel some sort of connection even when separated.

**Comment by CrispyJimbo** [comment]
Dancing isn't really something I like doing, but I'd be a fool to turn down any chance to "begin wildly shaking all parts of [my] body." The whole thing felt like a slow buildup to step 9, where I could finally wriggle and jiggle and writhe to my heart's content. I can definitely see the appeal of this kind of thing to help de-stress in a jail cell.

**Comment by arthurmosley** [comment]
As we are all in the middle of the semester (when things get hectic), performing this 10 step dance for solidarity actually relieved a lot of tension and anxiety both mentally and physically. I felt incredibly weird doing it but it was liberating. 

In terms of having a "Connection" to other people performing this dance, I can't say I did. I felt very isolated and honestly that was the best part of it: free form of expression without eyes of judgement. Overall I'm glad I gave it a legitimate shot and maybe there will be times where I bust out the moves again and possibly feel a connection to those I don't know.

**Comment by verghv5** [comment]
As Jordan has mentioned, I looked at this dance with an extreme amount of skepticism. I did not think it was properly productive or a means to relieve my stress. I can appreciate the benefits of the dance if there is literally nothing else to do. But as I am not currently in that situation, nor have I ever been in a similar situation, I simply could not find it a productive use of my time. It felt silly and ridiculous, and I cannot say that I would ever perform the 10 step dance again. I appreciate the sentiment greatly of what the dance represents, but it just is not for me.

**Comment by tcyrus** [comment]
I agree with the previous comment. It seems neat, but isn't something which I can relate to.

**Comment by youngcc3157** [comment]
The dance didn't really feel like dance but more of quick exercise. Some of the steps felt silly and pointless but I definitely enjoyed meditation-like exercise much better. I found it interesting yet did not feel any better or different than how I felt before the dance. I'd like to know what each step is supposed to do to a person mentally, physically, or emotionally.
