### ISSUE TITLE
Assignment 7: Letter to a Prisoner

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#14]
*Due Tuesday November 5.*

1. Listen to [episode 5 of Ear Hustle: Catch a Kite](https://www.earhustlesq.com/episodes/2017/8/09/catch-a-kite)
2. Follow the directions on the [Pink & Black penpal page](https://www.blackandpink.org/penpal-sign-up):  
    a. Review the Penpal Guidelines
    b. Read Important Things To Know & Do
    c. Choose your penpal (see also: [Political Prisoners in the USA](https://afgj.org/politicalprisonersusa))
    d. Optional: Fill out the [Pink & Black Penpal Form](https://www.blackandpink.org/penpal-form)
    e. Write to your Penpal (please let me know if you would like to use my mailing address as the return address)
    f. Bonus: Recruit Five Friends to Be Pen-Pals, Too!
3. Please add the name and location of the prisoner as a comment below.

**Comment by ChristinavanHal** [comment]
Name: Megan Canady
Location: Georgia

**Comment by schafc** [comment]
Name: Melinda
Location: Arizona

**Comment by mruskamp** [comment]
Name: Marcus Blackmon
Location: Hamilton County, Florida

**Comment by garoller** [comment]
Name: Bruce
Location: Pennsylvania

**Comment by youngcc3157** [comment]
Name: Phuong Nguyen
Location: Pine Knot, KY

**Comment by arthurmosley** [comment]
Name: Marc Mediate
Location: Wewahitchka, FL

**Comment by cmharsh** [comment]
Name: Ashley Hitner
Location: Elk Grove, CA

**Comment by verghv5** [comment]
Name: Hali Wilson
Location: Missouri

**Comment by bfblake** [comment]
Name: Richard Molina
Location: California

**Comment by Salomr** [comment]
Name: Ernest (Travis)
Location: Texas

**Comment by Brandonkl** [comment]
Name: Tracey
Location: Texas

**Comment by jordanchappel32** [comment]
Name: Chadrick Pate
Location: Huntsville, TX

**Comment by mlhawks12** [comment]
Name: Michael
Location: Arizona

**Comment by CrispyJimbo** [comment]
Name: Willie
Location: Texas

**Comment by KeranosGodofStorms** [comment]
Name: James
Location: Texas
