### ISSUE TITLE
Assignment 1: Hello, GitHub!

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#5]
1. [Sign up for GitHub](https://github.com/join) if you don't already have an account
2. Write a comment below, mostly so I'll have a list of everyone in the class.
3. Take a look at the [other issues](https://github.com/dphiffer/hacktivism/issues)—comment and/or leave emoji reactions as you feel moved to (especially interested in for suggestions for readings/videos/etc.)
* Advanced: make a pull request against this repo (you can reference this issue by including `#5` in the description)
* More advanced: see if you can run [Paul's software](https://github.com/ftrain/may142016), what are some hacktivist uses of it?

**Comment by dphiffer** [comment]
![IMG_1527](https://user-images.githubusercontent.com/38114/63657083-f0af6c80-c76a-11e9-98f4-c634a0786265.JPG)

**Comment by tcyrus** [comment]
Do you mind if I send a PR for the website code?

**Comment by dphiffer** [comment]
Yes, please do, @tcyrus, you are totally right that the cookie stuff could use more work.

**Comment by CrispyJimbo** [comment]
They don't call me "leaves a comment McGee" for nothing! Or at all.

**Comment by ChristinavanHal** [comment]
My name should be obvious...

**Comment by mruskamp** [comment]
Hey all, have a good week and looking forward to class on Tuesday.

**Comment by garoller** [comment]
Hello!

**Comment by bfblake** [comment]
See y'all tomorrow 👍🏼

**Comment by emma507** [comment]
Howdy! Looking forward to seeing y'all tomorrow!

**Comment by mlhawks12** [comment]
Hello y'all

**Comment by Salomr** [comment]
Forgot that I was supposed to leave a comment. Here it is!

**Comment by cmharsh** [comment]
Hi all,

Looking forward to seeing you all in class today evening.

Thx,

Cas

**Comment by arthurmosley** [comment]
Hello!

Excited for class tonight!

Arthur

**Comment by verghv5** [comment]
Hi,

Excited for class tonight 🔥🍁

Vivek

**Comment by youngcc3157** [comment]
Hello world

**Comment by Brandonkl** [comment]
Hello there

**Comment by KeranosGodofStorms** [comment]
finally here
