### ISSUE TITLE
Assignment 2: Food Forest

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#7]
* Take a look at the [Falling Fruit](https://fallingfruit.org/) map
* Use the map to find a fruit tree and take a photo of it
* Post your photo and a short description as a comment here
* Advanced: find a fruit tree that is _not_ on Falling Fruit and add it to the map (hint: check out [Collard City Growers](https://www.mediasanctuary.org/initiatives/collardcitygrowers/))
* More advanced: post your photo to [iNaturalist](https://www.inaturalist.org/) to identify the species

**Comment by ChristinavanHal** [comment]
![IMG_0876](https://user-images.githubusercontent.com/54903727/65467026-6a9c4980-de2e-11e9-9390-b004533f9657.jpg)
This is a rose I found on the corner of Burdett and People's. Near the building with parking services and the Rensselaer Dining Services. Roses produce rose hips, which I think count. The plant is blooming, so the rose hips will probably not be there for a few more weeks

**Comment by schafc** [comment]
![image](https://user-images.githubusercontent.com/55264495/65482782-23cb4580-de68-11e9-9b8a-f0405d343279.png)
A photo of the crabapple tree I found using the falling fruit map, located in the courtyard next to the DCC on RPI's main campus. The tree has crabapples on it at the moment, some of which have begun to fall off, so it seems like they are likely near the end of their growing season.
![image](https://user-images.githubusercontent.com/55264495/65482933-90dedb00-de68-11e9-96e6-80b24566c289.png)
I also found another tree that was not located on the falling fruit map, a different sort of crabapple tree with much smaller fruit than the first. It was located on congress street, between 7th and 8th street, on the city station parking lot side of the road. After doing some research, I determined that the smaller fruit is likely because the tree is an ornamental species, however the fruit is still edible, and can be used to make delicious jam.

**Comment by garoller** [comment]
This is a tree outside the Heffner Alumni House that is on the [map](https://fallingfruit.org/?z=17&y=42.73401&x=-73.68030&m=true&t=roadmap&l=false&locale=en&c=forager,freegan). The entry on the map doesn't say what kind of fruit tree it is, and it didn't look like it was bearing fruit yet.


![alumni](https://user-images.githubusercontent.com/22043215/65517278-6fa1dd00-deb0-11e9-94a6-58be5ea99871.jpg)

**Comment by mruskamp** [comment]
![IMG_0058](https://user-images.githubusercontent.com/23715603/65540377-46e20d80-ded9-11e9-9988-6311ffd1715f.jpg)

(Hopefully I've uploaded the image correctly) I found the above fruit tree around the parking garage on RPI campus, right down College Ave from Moe's.

Fallingfruit had one review for it that had this information to say about it:
Apple Malus  
Quality Good (1) Yield Good (1)
Unripe fruit September (1)

**Comment by Salomr** [comment]
![20190924_143426](https://user-images.githubusercontent.com/55164899/65540814-26668300-deda-11e9-8ae0-e6d358866c48.jpg)

(as with the previous hope this uploaded correctly)

This tree is actually on my fraternity's property. It currently bears these little red berries. Not exactly sure what kind, they don't look like raspberries or strawberries at all.

**Comment by cmharsh** [comment]
![File_001](https://user-images.githubusercontent.com/42871950/65545681-db516d80-dee3-11e9-880a-663c01c56dca.png)

Here is a picture I took today afternoon of a thicc cherry tree spotted thanks to the Falling Fruit map.  It is located on the walk-up along the footpath from the Student Union to Freshman Hill.

It is clearly quite succulent and is holding its fruit for quite a long time.

**Comment by jordanchappel32** [comment]
![71588571_2445201515738211_2226853252060676096_n](https://user-images.githubusercontent.com/55246815/65545902-587ce280-dee4-11e9-8d2c-63140c1c37c6.jpg)

This is a Cornelian Cherry tree near Folsom Library, found via the Falling Fruit map.

**Comment by jlyon1** [comment]
This is a crabapple tree outside sage building found via the Falling Fruit Map.


![IMG_0499](https://user-images.githubusercontent.com/6408853/65547309-3cc70b80-dee7-11e9-8a0e-f4645c2eef12.jpg)

**Comment by arthurmosley** [comment]
![image](https://user-images.githubusercontent.com/40047474/65547289-35076700-dee7-11e9-9746-0af29a587724.png)

Apple orchard found in front of the Lally Building.

**Comment by verghv5** [comment]
![8CD98686-6C07-48CA-938F-FBBB7D4CF981](https://user-images.githubusercontent.com/30439889/65549553-c37de780-deeb-11e9-9e73-2acaede4f957.jpeg)
West of Sage Labs, a cherry tree.

**Comment by bfblake** [comment]
![grape](https://user-images.githubusercontent.com/46270249/65553292-8b2ed700-def4-11e9-800a-cba1c90cfb1a.jpg)
 Grapes, down the street from Pizza Bell and easily accessible.

**Comment by mlhawks12** [comment]
![IMG_2421](https://user-images.githubusercontent.com/33819993/65554053-75baac80-def6-11e9-8883-589254db7acf.jpg)

**Comment by CrispyJimbo** [comment]
![IMG_20190924_212459701](https://user-images.githubusercontent.com/13438516/65561927-4c0f7e80-df12-11e9-93d7-b5b7c0f658fa.jpg)

A sinister night crab apple tree in Watervliet. Who knows what a spooky tree like this gets up to at night...

**Comment by dphiffer** [comment]
@tcyrus interesting, it seems to have turned into a PNG, but I'm guessing you uploaded as a JPG? It's a bit surprising that it would _format shift_ the image.

**Comment by tcyrus** [comment]
@dphiffer I uploaded a PNG. [PNG's can contain EXIF Data](https://stackoverflow.com/a/9576717)

**Comment by dphiffer** [comment]
@tcyrus I had no idea! And it looks like the values do not get stripped:

```
$ exiv2 -P E 13.png  
Exif.Image.ResolutionUnit                    Short       1  inch
Exif.Image.YCbCrPositioning                  Short       1  Centered
Exif.Image.GPSTag                            Long        1  50
Exif.GPSInfo.GPSLatitudeRef                  Ascii       2  North
Exif.GPSInfo.GPSLatitude                     Rational    3  42deg 44' 57.443" 
Exif.GPSInfo.GPSLongitudeRef                 Ascii       2  West
Exif.GPSInfo.GPSLongitude                    Rational    3  73deg 39' 38.917" 
```

**Comment by KeranosGodofStorms** [comment]
![IMG_5754](https://user-images.githubusercontent.com/56047170/66001955-96dc4980-e470-11e9-976a-d5a5cd3349c2.JPG)

![IMG_5755](https://user-images.githubusercontent.com/56047170/66001961-993ea380-e470-11e9-9ead-4ea41e53b922.JPG)

According to the Falling Fruit map these are crab apple trees that are located directly behind the RPI sign next to the Student Union.
