### ISSUE TITLE
Assignment 3: what things should be hacked?

### ISSUE THREAD

**Issue by dphiffer** [dphiffer/hacktivism#8]
What are three things that need to be hacked? Talk to some friends about this, and try to arrive at your strongest most convincing argument for *one thing that you think should be hacked*. Make an “elevator pitch” for the thing that needs hacking most.

Write your three things to be hacked in the comments below and be prepared to give a pitch for your _one thing that really should be hacked_ in class.

**Comment by mlhawks12** [comment]
MLB, Shirelys private email server, and Big Banks

**Comment by youngcc3157** [comment]
Area 51, White House, Banks

**Comment by ChristinavanHal** [comment]
Whoever runs the RPI title 9 cases (I've heard some disturbing rumors), White House (obvious reasons), super pac groups

**Comment by Salomr** [comment]
Police/FBI databases, nationwide security feeds, the Library of Congress

**Comment by tcyrus** [comment]
I personally think that industries should be hacked instead of specific institutions.

* [Education Calculators](https://www.numworks.com/)
* [Printing](https://hackaday.com/2010/01/26/why-arent-we-building-our-own-printers/)
* [Repair](https://en.wikipedia.org/wiki/Electronics_right_to_repair)

**Comment by arthurmosley** [comment]
I believe that the top 3 industries that should be hacked are the meat industry, college admissions, and formal education.

**Comment by cmharsh** [comment]
On the subject of which 3 industries/organizations ought to be hacked, I would postulate: The Clinton Family, the Democratic National Committee, and the chemical industry.

**Comment by schafc** [comment]
Three things that should be hacked are
-records of who donates to political candidates
-content filtering algorithms
-Government historical archives

**Comment by KeranosGodofStorms** [comment]
3 Things to be hacked:
-Albany Land Bank
-Youtube Databases
-Google Databases

**Comment by jlyon1** [comment]
- Course curriculums - more things need to be changed rather than "hacked", every class that is literally just a slide deck feels like a waste.
- Self Driving cars - If nothing happens here, we'll likely end up with vulnerabilities in our vehicles without tight enough regulations
- IOT devices - Idle compute time can be used for something significant

**Comment by Brandonkl** [comment]
- Big Pharma Companies
- Super Pacs
- Department of Education (Student Loans)

**Comment by bfblake** [comment]
- ICE
- 4Chan
- Reddit

**Comment by mruskamp** [comment]
I think 3 things that most need to be hacked are:
- any of several large industries, from alcohol to drug/pharmaceutical to finance
- Congress
- the FBI/CIA/NSA

**Comment by verghv5** [comment]
Software employment contracts (companies taking ownership of software developed after leaving the company).
The movie industry only making shitty live action remakes and superhero movies without actually taking risks with new and original ideas.
And finally, the DMV. It’s inefficiency knows no bounds and privatization could be a solution.

**Comment by CrispyJimbo** [comment]
communications in congress or other high political positions, the data collected from users of google/facebook/other big tech companies, and the oil industry.

**Comment by jordanchappel32** [comment]
I hope the class discussion is lively this evening! Some suggestions I have that aren't already on here: the NCAA, the Catholic Church, and job boards such as Indeed
