### ISSUE TITLE
Move Readings, Videos, and Events to Wiki

### ISSUE THREAD

**Issue by tcyrus** [dphiffer/hacktivism#9]
Move #1, #2, #4 to the [Wiki](https://github.com/dphiffer/hacktivism/wiki).

**Comment by dphiffer** [comment]
Hmm, yeah I'm not opposed to this.

**Comment by tcyrus** [comment]
I don't have edit access to the Wiki. I have posted the Issue dump to a Public [Gist](https://gist.github.com/tcyrus/2f2ea06905804e4a8670dd0fb947d817)

**Comment by tcyrus** [comment]
Closing Issue since class is over. I might also delete the gist soon.
